# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/david/Documents/work/dtcore32/vivado/dtcore32/dtcore32.runs/synth_1/dtcore32_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/david/Documents/work/dtcore32/vivado/dtcore32/dtcore32.cache/wt [current_project]
set_property parent.project_path /home/david/Documents/work/dtcore32/vivado/dtcore32/dtcore32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/david/Documents/work/dtcore32/vivado/dtcore32/dtcore32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog /home/david/Documents/work/dtcore32/src/macros.svh
set_property file_type "Verilog Header" [get_files /home/david/Documents/work/dtcore32/src/macros.svh]
read_mem {
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lui_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sra_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bltu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/andi_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/auipc_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/jal_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/xori_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lw_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/xor_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/xor_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sw_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/andi_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/auipc_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/fence_i_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sw_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srli_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lbu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sub_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sll_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sll_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srli_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/xori_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srl_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lh_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/fence_i_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lb_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slt_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/ori_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lw_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sltu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sb_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/blt_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/jal_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/or_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/and_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lhu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sra_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bltu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/beq_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bne_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/jalr_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/add_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slli_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sh_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sltiu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bgeu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srai_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/addi_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/add_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/addi_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/ma_data_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bge_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/ma_data_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/simple_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slti_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/simple_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slt_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slti_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lbu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sub_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/beq_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/blt_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bne_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bge_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sltiu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sh_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sltu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/sb_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/bgeu_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/jalr_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/ori_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lh_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lui_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/and_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lhu_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/or_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/slli_imem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srl_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/lb_dmem.mem
  /home/david/Documents/work/dtcore32/scripts/mem/hex/srai_dmem.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/david/Documents/work/dtcore32/src/dtcore32.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_EX_stage.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_ID_stage.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_IF_stage.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_MEM_stage.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_WB_stage.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_alu.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_decode_unit.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_dmem.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_hazard_unit.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_imem.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_regfile.sv
  /home/david/Documents/work/dtcore32/src/dtcore32_top.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/david/Documents/work/dtcore32/constr/arty.xdc
set_property used_in_implementation false [get_files /home/david/Documents/work/dtcore32/constr/arty.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/david/Documents/work/dtcore32/vivado/dtcore32/dtcore32.srcs/utils_1/imports/synth_1/dtcore32_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top dtcore32_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dtcore32_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file dtcore32_top_utilization_synth.rpt -pb dtcore32_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
