@startuml MASTER_WRITE
[*] --> IDLE
IDLE --> IDLE : else
IDLE --> WAIT_WRITE : [start = 1] / \nM_AWVALID = 1 \nM_WVALID = 1\
\nM_AWADDR = WRITE_ADDR \nM_AWDATA = WRITE_DATA \nM_BREADY = 1 \nM_WSTRB = 0xFF

WAIT_WRITE --> WAIT_WRITE : else
WAIT_WRITE --> WAIT_RESPONSE : [(S_AWREADY & S_WREADY) == 1] / \nS_AWVALID = 0 \nS_WVALID == 0

WAIT_RESPONSE --> WAIT_RESPONSE : else
WAIT_RESPONSE --> IDLE : [S_BVALID == 1] / RESPONSE_REG = S_BRESP



@enduml
