@startuml MASTER_READ
[*] --> READ_IDLE
READ_IDLE --> READ_IDLE : else / reset all outputs
READ_IDLE --> READ_ADDR : [start = 1] \nAXI_ARVALID = 1 \nAXI_RREADY = 1 \nAXI_ARADDR = RD_ADDR

READ_ADDR --> READ_ADDR : else
READ_ADDR --> READ_WAIT : [S_ARREADY = 1] \nM_ARVALID = 0 

READ_WAIT --> READ_WAIT : else
READ_WAIT --> READ_IDLE : [S_RVALID = 1] \nRRESP_MSG = AXI_RRESP \
\nAXI_RREADY = 0 \nRD_DATA = AXI_RDATA \
\nDONE = 1




@enduml
