@startuml MASTER_WRITE
[*] --> WRITE_IDLE
WRITE_IDLE --> WRITE_IDLE : else / reset all outputs
WRITE_IDLE --> WRITE_WAIT : [start = 1] / \nAXI_AWVALID = 1 \nAXI_WVALID = 1\
\nAXI_AWADDR = WR_ADDR \nAXI_WDATA = WR_DATA \nAXI_BREADY = 1 \nAXI_WSTRB = 0xFF

WRITE_WAIT --> WRITE_WAIT : else
WRITE_WAIT --> WRITE_RESP : [(AXI_AWREADY & AXI_WREADY) == 1] / \nAXI_AWVALID = 0 \nAXI_WVALID == 0

WRITE_RESP --> WRITE_RESP : else
WRITE_RESP --> WRITE_IDLE : [AXI_BVALID == 1] / \nBRESP_MSG = AXI_BRESP \nDONE = 1



@enduml
